---
abstract: 'Convenient and flexible config'
author:
  - 'Pronin Oleg <syber@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ConfigLoader-MultiState
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.71
  Class::Accessor::Grouped: 0
  File::Spec: 3.29
  MRO::Compat: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
